<a href="https://colab.research.google.com/github/visucs/100Day-of-ML/blob/main/Day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd


In [2]:

df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)


age  gender   review education purchased
35   74    Male     Poor    School       Yes
41   23    Male     Good        PG       Yes
21   32    Male  Average        PG        No
31   22  Female     Poor    School       Yes
11   74    Male     Good        UG       Yes

In [4]:
df = df.iloc[:,2:]


In [5]:
df.sample(5)

review education purchased
0   Average    School        No
47     Good        PG       Yes
26     Poor        PG        No
17     Poor        UG       Yes
20  Average    School       Yes

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [6]:
from sklearn.preprocessing import OrdinalEncoder


In [12]:
x_train

review education
18     Good    School
29  Average        UG
16     Poor        UG
30  Average        UG
14     Poor        PG
26     Poor        PG
49     Good        UG
47     Good        PG
12     Poor    School
38     Good    School
23     Good    School
4   Average        UG
33     Good        PG
22     Poor        PG
25     Good    School
3      Good        PG
45     Poor        PG
42     Good        PG
9      Good        UG
46     Poor        PG
21  Average        PG
19     Poor        PG
15     Poor        UG
20  Average    School
24  Average        PG
28     Poor    School
2      Good        PG
5   Average    School
1      Poor        UG
34  Average    School
37  Average        PG
7      Poor    School
17     Poor        UG
27     Poor        PG
32  Average        UG
0   Average    School
43     Poor        PG
36     Good        UG
44  Average        UG
40     Good    School

In [13]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [18]:
x_train = oe.transform(x_train)

In [19]:
x_train

array([[2., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.]])

In [20]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [22]:
x_train

array([[2., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.]])

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

In [25]:
le.fit(y_train)

LabelEncoder()

In [26]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [27]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)


In [28]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0])